choose-file = Datei auswählen
zh-CN = 简体中文
en-US = English
ja-JP = 日本語
ko-KR = 한국어
es-ES = Español
fr-FR = Français
de-DE = Deutsch
supported-files = Unterstützte Dateien
drag-and-drop-file-here = Datei hierher ziehen und ablegen
file = Datei
extension = Erweiterung
file-type-header = Dateityp
extension-header = Erweiterung
category-header = Kategorie
pdf-file = PDF-Datei
epub-file = EPub-Datei
mobi-file = Mobi-Datei
azw3-file = Azw3-Datei
archive-file = Archivdatei
guitar-tab-file = Gitarrentab-Datei
threed-model-file = 3D-Modelldatei
loading = Laden
loading-failure = Laden fehlgeschlagen
password-dialog-title = Passwort
password-label = Passwort
password-input =
  .placeholder = Passwort eingeben
submit = Absenden
torrent-file = Torrent-Datei
download = Herunterladen
preview = Vorschau
prev = Zurück
next = Weiter
project-privacy-statement = Diese Website ist ein persönliches Projekt. Sie dient zur Vorschau von Dateien. Es werden keine Dateien hochgeladen oder gespeichert. Bitte nicht als Cloud-Speicher verwenden.
support-and-feedback-statement = Da es nicht vollständig getestet wurde, können beim Öffnen einiger Dateien, insbesondere großer Dateien, Probleme auftreten. Wenn Sie Probleme finden, können Sie ein Issue auf Github erstellen, aber es gibt keine Garantie, dass es sofort behoben wird.
offline-support-statement = Sobald diese Website vollständig geladen ist, sollte sie offline funktionieren, es sei denn, Sie installieren Ihren Browser neu oder löschen den Browserspeicher.
default-viewer = Standard-Viewer
text = Text
binary = Binär
file-is-too-large = Datei ist zu groß
csv-file = CSV-Datei
wasm-file = WASM-Datei
audio-file = Audiodatei
video-file = Videodatei
image-file = Bilddatei
email-file = E-Mail-Datei
transcoding = Transkodierung
from = Von
to = An
subject = Betreff
attachments = Anhänge
no-file-selected = Keine Datei ausgewählt
back-to-home = Zurück zur Startseite
please-select-file = Bitte wählen Sie eine Datei zum Anzeigen
