choose-file = Datei auswählen
zh-CN = 简体中文
en-US = English
ja-JP = 日本語
ko-KR = 한국어
es-ES = Español
fr-FR = Français
de-DE = Deutsch
supported-files = Unterstützte Dateien
drag-and-drop-file-here = Datei hierher ziehen und ablegen
file = Datei
extension = Erweiterung
file-type-header = Dateityp
extension-header = Erweiterung
category-header = Kategorie
pdf-file = PDF-Datei
word-file = Word-Dokument
excel-file = Excel-Tabelle
powerpoint-file = PowerPoint-Präsentation
rtf-file = Rich-Text-Dokument
opendocument-file = OpenDocument-Datei
slide = Folie
markdown-file = Markdown-Dokument
epub-file = EPub-Datei
mobi-file = Mobi-Datei
azw3-file = Azw3-Datei
archive-file = Archivdatei
guitar-tab-file = Gitarrentab-Datei
threed-model-file = 3D-Modelldatei
loading = Laden
loading-failure = Laden fehlgeschlagen
password-dialog-title = Passwort
password-label = Passwort
password-input =
  .placeholder = Passwort eingeben
submit = Absenden
torrent-file = Torrent-Datei
download = Herunterladen
preview = Vorschau
prev = Zurück
next = Weiter
speaker-notes = Sprechernotizen
empty-sheet = Dieses Blatt ist leer
sizes = Größen
paragraph = Absatz
characters = Zeichen
numbers = Zahlen
symbols = Symbole
project-privacy-statement = Diese Website ist ein persönliches Projekt. Sie dient zur Vorschau von Dateien. Es werden keine Dateien hochgeladen oder gespeichert. Bitte nicht als Cloud-Speicher verwenden.
support-and-feedback-statement = Da es nicht vollständig getestet wurde, können beim Öffnen einiger Dateien, insbesondere großer Dateien, Probleme auftreten. Wenn Sie Probleme finden, können Sie ein Issue auf Github erstellen, aber es gibt keine Garantie, dass es sofort behoben wird.
offline-support-statement = Sobald diese Website vollständig geladen ist, sollte sie offline funktionieren, es sei denn, Sie installieren Ihren Browser neu oder löschen den Browserspeicher.
default-viewer = Standard-Viewer
text = Text
binary = Binär
file-is-too-large = Datei ist zu groß
csv-file = CSV-Datei
sqlite-file = SQLite-Datenbank
tables = Tabellen
rows = Zeilen
columns = Spalten
empty-table = Diese Tabelle ist leer
select-table = Wählen Sie eine Tabelle aus, um Daten anzuzeigen
wasm-file = WASM-Datei
audio-file = Audiodatei
video-file = Videodatei
subtitle-file = Untertiteldatei
subtitles = Untertitel
image-file = Bilddatei
email-file = E-Mail-Datei
code-file = Quellcode
ical-file = Kalender/Kontakt-Datei
calendar-events = Kalendertermine
events = Termine
contacts = Kontakte
contacts-count = Kontakte
comic-file = Comic-Archiv
single-page = Einzelseite
double-page = Doppelseite
tree-file = Strukturierte Datendatei
expand-all = Alles erweitern
collapse-all = Alles einklappen
search = Suchen...
nodes = Knoten
log-file = Protokolldatei
search-logs = Protokolle durchsuchen...
showing = Anzeige
lines = Zeilen
no-results = Keine passenden Einträge gefunden
empty-log = Keine Protokolleinträge zum Anzeigen
config-file = Konfigurationsdatei
sections = Abschnitte
empty-config = Keine Konfigurationseinträge gefunden
hex-file = Binärdatei
offset = Offset
ascii = ASCII
bytes-per-row = Bytes/Zeile
jump-to = Gehe zu
loaded = Geladen
truncated = abgeschnitten
diff-file = Diff/Patch-Datei
files-changed = Dateien geändert
additions = Hinzufügungen
deletions = Löschungen
new = Neu
deleted = Gelöscht
renamed = Umbenannt
binary = Binär
binary-file = Binärdatei nicht angezeigt
empty-diff = Kein Diff-Inhalt gefunden
certificate-file = Zertifikatsdatei
certificate = Zertifikat
private-key = Privater Schlüssel
public-key = Öffentlicher Schlüssel
certificate-request = Zertifikatsanfrage
fingerprints = Fingerabdrücke
raw-content = Rohinhalt
word-wrap = Zeilenumbruch
transcoding = Transkodierung
from = Von
to = An
subject = Betreff
attachments = Anhänge
no-file-selected = Keine Datei ausgewählt
back-to-home = Zurück zur Startseite
back = Zurück
menu = Menü
switch-theme = Design
please-select-file = Bitte wählen Sie eine Datei zum Anzeigen
open-source-credits = Open-Source-Credits
credits-intro = Web Explorer steht auf den Schultern von Riesen. Wir danken allen Open-Source-Projekten, die diese Anwendung möglich machen.
credits-footer = Mit Liebe unter Verwendung von Open-Source-Software erstellt
contact = Kontakt
feedback = Feedback
unsupported-file = Nicht Unterstützter Dateityp
unsupported-file-message = Dieser Dateityp wird derzeit nicht unterstützt. Wenn Sie möchten, dass wir Unterstützung für dieses Format hinzufügen, lassen Sie es uns wissen!
request-support = Support Anfragen

# Eingabebereich
drop-or-paste = Datei ablegen oder Inhalt einfügen
drop-paste-hint = Ziehen Sie eine Datei hierher, oder drücken Sie Strg+V zum Einfügen
privacy-notice = Ihre Datei wird nicht hochgeladen. Die gesamte Verarbeitung erfolgt lokal in Ihrem Browser.

# Theme-Umschalter
switch-to-light = Zum hellen Modus wechseln
switch-to-dark = Zum dunklen Modus wechseln

# Fiddler-Viewer
fiddler-file = Fiddler-Sitzungsarchiv
sessions = Sitzungen
method = Methode
url = URL
status = Status
request = Anfrage
response = Antwort
timers = Timer
headers = Header
body = Inhalt
no-sessions = Keine HTTP-Sitzungen gefunden
select-session = Sitzung auswählen, um Details anzuzeigen

# Zwischenablage-Viewer
clipboard-file = Zwischenablage-Daten
formats-available = Format(e) verfügbar
html-source = HTML-Quellcode
failed-to-parse-clipboard = Fehler beim Parsen der Zwischenablage-Daten
no-data = Keine Daten
clear = Löschen
