choose-file = Choose File
zh-CN = 简体中文
en-US = English
ja-JP = 日本語
ko-KR = 한국어
es-ES = Español
fr-FR = Français
de-DE = Deutsch
supported-files = Supported Files
drag-and-drop-file-here = Drag and drop file here
file = File
extension = Extension
file-type-header = File Type
extension-header = Extension
category-header = Category
pdf-file = PDF File
word-file = Word Document
excel-file = Excel Spreadsheet
powerpoint-file = PowerPoint Presentation
rtf-file = Rich Text Document
epub-file = EPub File
mobi-file = Mobi File
azw3-file = Azw3 File
archive-file = Archive File
guitar-tab-file = GuitarPro File
threed-model-file = 3D Model File
loading = Loading
loading-failure = Loading Failure
password-dialog-title = Password
password-label = Password
password-input =
  .placeholder = Input password
submit = Submit
torrent-file = Torrent File
download = Download
preview = Preview
prev = Prev
next = Next
speaker-notes = Speaker Notes
empty-sheet = This sheet is empty
project-privacy-statement = This website is a personal project. It's build for previewing files, especially when you get some files and you don't have any applications to open it. Do note that it won't upload or save your files to any places, don't use this as cloud storage.
support-and-feedback-statement = Since it's not fully tested, it might have problems when opening some files, especially when the file is huge. If you find any problems, you can create an issue at Github, there's no guarantee that it will be fixed immediately though.
offline-support-statement = Once this website is fully loaded, it should be able to work offline if you don't reinstall your browser or clear your browser storage.
default-viewer = Default Viewer
text = Text
binary = Binary
file-is-too-large = File is too large
csv-file = CSV File
wasm-file = WASM File
audio-file = Audio File
video-file = Video File
image-file = Image File
email-file = Email File
code-file = Source Code
transcoding = Transcoding
from = From
to = To
subject = Subject
attachments = Attachments
no-file-selected = No File Selected
back-to-home = Back to Home
please-select-file = Please select a file to view

# Create File Page
create-new-file = Create New File
file-type = File Type
describe-file = Describe Your File
prompt-placeholder = Describe what should be included in the file, the layout/structure, or any specific requirements...
prompt-hint = Be as specific as possible about the content, structure, and formatting you want.
create-file = Create File
customize = Customize
customize-placeholder = Enter additional instructions to modify the file...
start-over = Start Over
apply-changes = Apply Changes
file-created = Your file has been created!
create-another = Create Another
customize-further = Want to customize it?
try-again = Try Again
connected = Connected
disconnected = Disconnected
starting-creation = Starting file creation...
customizing-file = Customizing file...
initializing = Connecting to server...
connection-failed = Failed to connect to server