choose-file = Choose File
zh-CN = 简体中文
en-US = English
ja-JP = 日本語
ko-KR = 한국어
es-ES = Español
fr-FR = Français
de-DE = Deutsch
supported-files = Supported Files
drag-and-drop-file-here = Drag and drop file here
file = File
extension = Extension
file-type-header = File Type
extension-header = Extension
category-header = Category
pdf-file = PDF File
word-file = Word Document
excel-file = Excel Spreadsheet
powerpoint-file = PowerPoint Presentation
rtf-file = Rich Text Document
opendocument-file = OpenDocument File
slide = Slide
markdown-file = Markdown Document
epub-file = EPub File
mobi-file = Mobi File
azw3-file = Azw3 File
archive-file = Archive File
guitar-tab-file = GuitarPro File
threed-model-file = 3D Model File
loading = Loading
loading-failure = Loading Failure
password-dialog-title = Password
password-label = Password
password-input =
  .placeholder = Input password
submit = Submit
torrent-file = Torrent File
download = Download
preview = Preview
prev = Prev
next = Next
speaker-notes = Speaker Notes
empty-sheet = This sheet is empty
sizes = Sizes
paragraph = Paragraph
characters = Characters
numbers = Numbers
symbols = Symbols
project-privacy-statement = This website is a personal project. It's build for previewing files, especially when you get some files and you don't have any applications to open it. Do note that it won't upload or save your files to any places, don't use this as cloud storage.
support-and-feedback-statement = Since it's not fully tested, it might have problems when opening some files, especially when the file is huge. If you find any problems, you can create an issue at Github, there's no guarantee that it will be fixed immediately though.
offline-support-statement = Once this website is fully loaded, it should be able to work offline if you don't reinstall your browser or clear your browser storage.
default-viewer = Default Viewer
text = Text
binary = Binary
file-is-too-large = File is too large
csv-file = CSV File
sqlite-file = SQLite Database
tables = Tables
rows = rows
columns = columns
empty-table = This table is empty
select-table = Select a table to view data
wasm-file = WASM File
audio-file = Audio File
video-file = Video File
subtitle-file = Subtitle File
subtitles = subtitles
image-file = Image File
email-file = Email File
code-file = Source Code
ical-file = Calendar/Contact File
calendar-events = Calendar Events
events = events
contacts = Contacts
contacts-count = contacts
comic-file = Comic Book Archive
single-page = Single Page
double-page = Double Page
tree-file = Structured Data File
expand-all = Expand All
collapse-all = Collapse All
search = Search...
nodes = nodes
log-file = Log File
search-logs = Search logs...
showing = Showing
lines = lines
no-results = No matching entries found
empty-log = No log entries to display
config-file = Configuration File
sections = Sections
empty-config = No configuration entries found
hex-file = Binary File
offset = Offset
ascii = ASCII
bytes-per-row = Bytes/Row
jump-to = Jump to
loaded = Loaded
truncated = truncated
diff-file = Diff/Patch File
files-changed = files changed
additions = additions
deletions = deletions
new = New
deleted = Deleted
renamed = Renamed
binary = Binary
binary-file = Binary file not shown
empty-diff = No diff content found
certificate-file = Certificate File
certificate = Certificate
private-key = Private Key
public-key = Public Key
certificate-request = Certificate Request
fingerprints = Fingerprints
raw-content = Raw Content
word-wrap = Word Wrap
transcoding = Transcoding
from = From
to = To
subject = Subject
attachments = Attachments
no-file-selected = No File Selected
back-to-home = Back to Home
back = Back
menu = Menu
switch-theme = Theme
please-select-file = Please select a file to view

# Create File Page
create-new-file = Create New File
file-type = File Type
describe-file = Describe Your File
prompt-placeholder = Describe what should be included in the file, the layout/structure, or any specific requirements...
prompt-hint = Be as specific as possible about the content, structure, and formatting you want.
create-file = Create File
customize = Customize
customize-placeholder = Enter additional instructions to modify the file...
start-over = Start Over
apply-changes = Apply Changes
file-created = Your file has been created!
create-another = Create Another
customize-further = Want to customize it?
try-again = Try Again
connected = Connected
disconnected = Disconnected
starting-creation = Starting file creation...
customizing-file = Customizing file...
initializing = Connecting to server...
connection-failed = Failed to connect to server
open-source-credits = Open Source Credits
credits-intro = Web Explorer is built on the shoulders of giants. We are grateful to all the open source projects that make this application possible.
credits-footer = Made with love using open source software
contact = Contact
feedback = Feedback
unsupported-file = Unsupported File Type
unsupported-file-message = This file type is not currently supported. If you would like us to add support for this format, please let us know!
request-support = Request Support

# Input Zone
drop-or-paste = Drop file or paste content
drop-paste-hint = Drag and drop a file, or press Ctrl+V to paste

# Theme Toggle
switch-to-light = Switch to light mode
switch-to-dark = Switch to dark mode

# Fiddler Viewer
fiddler-file = Fiddler Session Archive
sessions = sessions
method = Method
url = URL
status = Status
request = Request
response = Response
timers = Timers
headers = Headers
body = Body
no-sessions = No HTTP sessions found
select-session = Select a session to view details

# Clipboard Viewer
clipboard-file = Clipboard Data
formats-available = format(s) available
html-source = HTML Source
failed-to-parse-clipboard = Failed to parse clipboard data
no-data = No data
clear = Clear