choose-file = Seleccionar archivo
zh-CN = 简体中文
en-US = English
ja-JP = 日本語
ko-KR = 한국어
es-ES = Español
fr-FR = Français
de-DE = Deutsch
supported-files = Archivos compatibles
drag-and-drop-file-here = Arrastra y suelta el archivo aquí
file = Archivo
extension = Extensión
file-type-header = Tipo de archivo
extension-header = Extensión
category-header = Categoría
pdf-file = Archivo PDF
word-file = Documento Word
excel-file = Hoja de cálculo Excel
powerpoint-file = Presentación PowerPoint
rtf-file = Documento de texto enriquecido
opendocument-file = Archivo OpenDocument
slide = Diapositiva
markdown-file = Documento Markdown
epub-file = Archivo EPub
mobi-file = Archivo Mobi
azw3-file = Archivo Azw3
archive-file = Archivo comprimido
guitar-tab-file = Archivo de tablatura
threed-model-file = Archivo de modelo 3D
loading = Cargando
loading-failure = Error al cargar
password-dialog-title = Contraseña
password-label = Contraseña
password-input =
  .placeholder = Ingrese contraseña
submit = Enviar
torrent-file = Archivo Torrent
download = Descargar
preview = Vista previa
prev = Anterior
next = Siguiente
speaker-notes = Notas del orador
empty-sheet = Esta hoja está vacía
sizes = Tamaños
paragraph = Párrafo
characters = Caracteres
numbers = Números
symbols = Símbolos
project-privacy-statement = Este sitio web es un proyecto personal. Está diseñado para previsualizar archivos. No se subirán ni guardarán archivos en ningún lugar. No lo use como almacenamiento en la nube.
support-and-feedback-statement = Como no está completamente probado, puede tener problemas al abrir algunos archivos, especialmente los grandes. Si encuentra algún problema, puede crear un issue en Github, aunque no hay garantía de que se solucione inmediatamente.
offline-support-statement = Una vez que este sitio web se haya cargado completamente, debería poder funcionar sin conexión a menos que reinstale su navegador o borre el almacenamiento del navegador.
default-viewer = Visor predeterminado
text = Texto
binary = Binario
file-is-too-large = El archivo es demasiado grande
csv-file = Archivo CSV
sqlite-file = Base de datos SQLite
tables = Tablas
rows = filas
columns = columnas
empty-table = Esta tabla está vacía
select-table = Seleccione una tabla para ver los datos
wasm-file = Archivo WASM
audio-file = Archivo de audio
video-file = Archivo de video
subtitle-file = Archivo de subtítulos
subtitles = subtítulos
image-file = Archivo de imagen
email-file = Archivo de correo
code-file = Código fuente
ical-file = Archivo de calendario/contacto
calendar-events = Eventos del calendario
events = eventos
contacts = Contactos
contacts-count = contactos
comic-file = Archivo de cómic
single-page = Página simple
double-page = Doble página
tree-file = Archivo de datos estructurados
expand-all = Expandir todo
collapse-all = Contraer todo
search = Buscar...
nodes = nodos
log-file = Archivo de registro
search-logs = Buscar registros...
showing = Mostrando
lines = líneas
no-results = No se encontraron entradas coincidentes
empty-log = No hay entradas de registro para mostrar
config-file = Archivo de configuración
sections = Secciones
empty-config = No se encontraron entradas de configuración
hex-file = Archivo binario
offset = Desplazamiento
ascii = ASCII
bytes-per-row = Bytes/Fila
jump-to = Ir a
loaded = Cargado
truncated = truncado
diff-file = Archivo Diff/Patch
files-changed = archivos modificados
additions = adiciones
deletions = eliminaciones
new = Nuevo
deleted = Eliminado
renamed = Renombrado
binary = Binario
binary-file = Archivo binario no mostrado
empty-diff = No se encontró contenido diff
certificate-file = Archivo de certificado
certificate = Certificado
private-key = Clave privada
public-key = Clave pública
certificate-request = Solicitud de certificado
fingerprints = Huellas digitales
raw-content = Contenido sin procesar
word-wrap = Ajuste de línea
transcoding = Transcodificando
from = De
to = Para
subject = Asunto
attachments = Adjuntos
no-file-selected = Ningún archivo seleccionado
back-to-home = Volver al inicio
please-select-file = Por favor seleccione un archivo para ver
open-source-credits = Créditos de Código Abierto
credits-intro = Web Explorer está construido sobre los hombros de gigantes. Agradecemos a todos los proyectos de código abierto que hacen posible esta aplicación.
credits-footer = Hecho con ❤️ usando software de código abierto
contact = Contacto
feedback = Comentarios
unsupported-file = Tipo de Archivo No Soportado
unsupported-file-message = Este tipo de archivo no está soportado actualmente. Si desea que agreguemos soporte para este formato, ¡háganoslo saber!
request-support = Solicitar Soporte
