choose-file = Seleccionar archivo
zh-CN = 简体中文
en-US = English
ja-JP = 日本語
ko-KR = 한국어
es-ES = Español
fr-FR = Français
de-DE = Deutsch
supported-files = Archivos compatibles
drag-and-drop-file-here = Arrastra y suelta el archivo aquí
file = Archivo
extension = Extensión
file-type-header = Tipo de archivo
extension-header = Extensión
category-header = Categoría
pdf-file = Archivo PDF
epub-file = Archivo EPub
mobi-file = Archivo Mobi
azw3-file = Archivo Azw3
archive-file = Archivo comprimido
guitar-tab-file = Archivo de tablatura
threed-model-file = Archivo de modelo 3D
loading = Cargando
loading-failure = Error al cargar
password-dialog-title = Contraseña
password-label = Contraseña
password-input =
  .placeholder = Ingrese contraseña
submit = Enviar
torrent-file = Archivo Torrent
download = Descargar
preview = Vista previa
prev = Anterior
next = Siguiente
project-privacy-statement = Este sitio web es un proyecto personal. Está diseñado para previsualizar archivos. No se subirán ni guardarán archivos en ningún lugar. No lo use como almacenamiento en la nube.
support-and-feedback-statement = Como no está completamente probado, puede tener problemas al abrir algunos archivos, especialmente los grandes. Si encuentra algún problema, puede crear un issue en Github, aunque no hay garantía de que se solucione inmediatamente.
offline-support-statement = Una vez que este sitio web se haya cargado completamente, debería poder funcionar sin conexión a menos que reinstale su navegador o borre el almacenamiento del navegador.
default-viewer = Visor predeterminado
text = Texto
binary = Binario
file-is-too-large = El archivo es demasiado grande
csv-file = Archivo CSV
wasm-file = Archivo WASM
audio-file = Archivo de audio
video-file = Archivo de video
image-file = Archivo de imagen
email-file = Archivo de correo
transcoding = Transcodificando
from = De
to = Para
subject = Asunto
attachments = Adjuntos
no-file-selected = Ningún archivo seleccionado
back-to-home = Volver al inicio
please-select-file = Por favor seleccione un archivo para ver
