choose-file = Choisir un fichier
zh-CN = 简体中文
en-US = English
ja-JP = 日本語
ko-KR = 한국어
es-ES = Español
fr-FR = Français
de-DE = Deutsch
supported-files = Fichiers pris en charge
drag-and-drop-file-here = Glissez et déposez le fichier ici
file = Fichier
extension = Extension
file-type-header = Type de fichier
extension-header = Extension
category-header = Catégorie
pdf-file = Fichier PDF
word-file = Document Word
excel-file = Feuille de calcul Excel
powerpoint-file = Présentation PowerPoint
rtf-file = Document texte enrichi
opendocument-file = Fichier OpenDocument
slide = Diapositive
markdown-file = Document Markdown
epub-file = Fichier EPub
mobi-file = Fichier Mobi
azw3-file = Fichier Azw3
archive-file = Fichier archive
guitar-tab-file = Fichier tablature
threed-model-file = Fichier modèle 3D
loading = Chargement
loading-failure = Échec du chargement
password-dialog-title = Mot de passe
password-label = Mot de passe
password-input =
  .placeholder = Entrez le mot de passe
submit = Soumettre
torrent-file = Fichier Torrent
download = Télécharger
preview = Aperçu
prev = Précédent
next = Suivant
speaker-notes = Notes du présentateur
empty-sheet = Cette feuille est vide
sizes = Tailles
paragraph = Paragraphe
characters = Caractères
numbers = Chiffres
symbols = Symboles
project-privacy-statement = Ce site web est un projet personnel. Il est conçu pour prévisualiser des fichiers. Aucun fichier ne sera téléchargé ou enregistré nulle part. Ne l'utilisez pas comme stockage cloud.
support-and-feedback-statement = Comme il n'est pas entièrement testé, il peut y avoir des problèmes lors de l'ouverture de certains fichiers, surtout les gros. Si vous trouvez des problèmes, vous pouvez créer une issue sur Github, mais il n'y a aucune garantie qu'elle sera résolue immédiatement.
offline-support-statement = Une fois ce site web entièrement chargé, il devrait pouvoir fonctionner hors ligne à moins que vous ne réinstalliez votre navigateur ou ne vidiez le stockage du navigateur.
default-viewer = Visionneuse par défaut
text = Texte
binary = Binaire
file-is-too-large = Le fichier est trop volumineux
csv-file = Fichier CSV
sqlite-file = Base de données SQLite
tables = Tables
rows = lignes
columns = colonnes
empty-table = Cette table est vide
select-table = Sélectionnez une table pour voir les données
wasm-file = Fichier WASM
audio-file = Fichier audio
video-file = Fichier vidéo
subtitle-file = Fichier de sous-titres
subtitles = sous-titres
image-file = Fichier image
email-file = Fichier email
code-file = Code source
ical-file = Fichier calendrier/contact
calendar-events = Événements du calendrier
events = événements
contacts = Contacts
contacts-count = contacts
comic-file = Archive de bande dessinée
single-page = Page simple
double-page = Double page
tree-file = Fichier de données structurées
expand-all = Tout déplier
collapse-all = Tout replier
search = Rechercher...
nodes = nœuds
log-file = Fichier journal
search-logs = Rechercher dans les logs...
showing = Affichage
lines = lignes
no-results = Aucune entrée correspondante trouvée
empty-log = Aucune entrée de journal à afficher
config-file = Fichier de configuration
sections = Sections
empty-config = Aucune entrée de configuration trouvée
hex-file = Fichier binaire
offset = Décalage
ascii = ASCII
bytes-per-row = Octets/Ligne
jump-to = Aller à
loaded = Chargé
truncated = tronqué
diff-file = Fichier Diff/Patch
files-changed = fichiers modifiés
additions = ajouts
deletions = suppressions
new = Nouveau
deleted = Supprimé
renamed = Renommé
binary = Binaire
binary-file = Fichier binaire non affiché
empty-diff = Aucun contenu diff trouvé
certificate-file = Fichier certificat
certificate = Certificat
private-key = Clé privée
public-key = Clé publique
certificate-request = Demande de certificat
fingerprints = Empreintes
raw-content = Contenu brut
word-wrap = Retour à la ligne
transcoding = Transcodage
from = De
to = À
subject = Sujet
attachments = Pièces jointes
no-file-selected = Aucun fichier sélectionné
back-to-home = Retour à l'accueil
back = Retour
menu = Menu
switch-theme = Thème
please-select-file = Veuillez sélectionner un fichier à afficher
open-source-credits = Crédits Open Source
credits-intro = Web Explorer est construit sur les épaules de géants. Nous remercions tous les projets open source qui rendent cette application possible.
credits-footer = Fait avec amour en utilisant des logiciels open source
contact = Contact
feedback = Retour d'information
unsupported-file = Type de Fichier Non Supporté
unsupported-file-message = Ce type de fichier n'est pas supporté actuellement. Si vous souhaitez que nous ajoutions le support de ce format, faites-le nous savoir !
request-support = Demander le Support

# Zone d'entrée
drop-or-paste = Déposez un fichier ou collez du contenu
drop-paste-hint = Glissez-déposez un fichier, ou appuyez sur Ctrl+V pour coller

# Changement de thème
switch-to-light = Passer au mode clair
switch-to-dark = Passer au mode sombre

# Visionneuse Fiddler
fiddler-file = Archive de Session Fiddler
sessions = sessions
method = Méthode
url = URL
status = Statut
request = Requête
response = Réponse
timers = Minuteries
headers = En-têtes
body = Corps
no-sessions = Aucune session HTTP trouvée
select-session = Sélectionnez une session pour voir les détails

# Visionneuse du Presse-papiers
clipboard-file = Données du Presse-papiers
formats-available = format(s) disponible(s)
html-source = Code HTML
failed-to-parse-clipboard = Échec de l'analyse des données du presse-papiers
no-data = Aucune donnée
clear = Effacer
