choose-file = Choisir un fichier
zh-CN = 简体中文
en-US = English
ja-JP = 日本語
ko-KR = 한국어
es-ES = Español
fr-FR = Français
de-DE = Deutsch
supported-files = Fichiers pris en charge
drag-and-drop-file-here = Glissez et déposez le fichier ici
file = Fichier
extension = Extension
file-type-header = Type de fichier
extension-header = Extension
category-header = Catégorie
pdf-file = Fichier PDF
epub-file = Fichier EPub
mobi-file = Fichier Mobi
azw3-file = Fichier Azw3
archive-file = Fichier archive
guitar-tab-file = Fichier tablature
threed-model-file = Fichier modèle 3D
loading = Chargement
loading-failure = Échec du chargement
password-dialog-title = Mot de passe
password-label = Mot de passe
password-input =
  .placeholder = Entrez le mot de passe
submit = Soumettre
torrent-file = Fichier Torrent
download = Télécharger
preview = Aperçu
prev = Précédent
next = Suivant
project-privacy-statement = Ce site web est un projet personnel. Il est conçu pour prévisualiser des fichiers. Aucun fichier ne sera téléchargé ou enregistré nulle part. Ne l'utilisez pas comme stockage cloud.
support-and-feedback-statement = Comme il n'est pas entièrement testé, il peut y avoir des problèmes lors de l'ouverture de certains fichiers, surtout les gros. Si vous trouvez des problèmes, vous pouvez créer une issue sur Github, mais il n'y a aucune garantie qu'elle sera résolue immédiatement.
offline-support-statement = Une fois ce site web entièrement chargé, il devrait pouvoir fonctionner hors ligne à moins que vous ne réinstalliez votre navigateur ou ne vidiez le stockage du navigateur.
default-viewer = Visionneuse par défaut
text = Texte
binary = Binaire
file-is-too-large = Le fichier est trop volumineux
csv-file = Fichier CSV
wasm-file = Fichier WASM
audio-file = Fichier audio
video-file = Fichier vidéo
image-file = Fichier image
email-file = Fichier email
transcoding = Transcodage
from = De
to = À
subject = Sujet
attachments = Pièces jointes
no-file-selected = Aucun fichier sélectionné
back-to-home = Retour à l'accueil
please-select-file = Veuillez sélectionner un fichier à afficher
