choose-file = 파일 선택
zh-CN = 简体中文
en-US = English
ja-JP = 日本語
ko-KR = 한국어
es-ES = Español
fr-FR = Français
de-DE = Deutsch
supported-files = 지원 파일
drag-and-drop-file-here = 여기에 파일을 드래그 앤 드롭하세요
file = 파일
extension = 확장자
file-type-header = 파일 유형
extension-header = 확장자
category-header = 카테고리
pdf-file = PDF 파일
word-file = Word 문서
excel-file = Excel 스프레드시트
powerpoint-file = PowerPoint 프레젠테이션
rtf-file = 서식 있는 텍스트 문서
epub-file = EPub 파일
mobi-file = Mobi 파일
azw3-file = Azw3 파일
archive-file = 압축 파일
guitar-tab-file = 기타 탭 파일
threed-model-file = 3D 모델 파일
loading = 로딩 중
loading-failure = 로딩 실패
password-dialog-title = 비밀번호
password-label = 비밀번호
password-input =
  .placeholder = 비밀번호 입력
submit = 제출
torrent-file = Torrent 파일
download = 다운로드
preview = 미리보기
prev = 이전
next = 다음
speaker-notes = 발표자 노트
empty-sheet = 이 시트는 비어 있습니다
project-privacy-statement = 이 웹사이트는 개인 프로젝트입니다. 파일 미리보기를 위해 만들어졌습니다. 파일은 어디에도 업로드하거나 저장하지 않습니다. 클라우드 스토리지로 사용하지 마세요.
support-and-feedback-statement = 완전히 테스트되지 않았기 때문에 일부 파일, 특히 큰 파일을 열 때 문제가 발생할 수 있습니다. 문제를 발견하면 Github에서 이슈를 만들 수 있지만, 즉시 수정된다는 보장은 없습니다.
offline-support-statement = 이 웹사이트가 완전히 로드되면 브라우저를 재설치하거나 브라우저 저장소를 지우지 않는 한 오프라인에서 작동합니다.
default-viewer = 기본 뷰어
text = 텍스트
binary = 바이너리
file-is-too-large = 파일이 너무 큽니다
csv-file = CSV 파일
wasm-file = WASM 파일
audio-file = 오디오 파일
video-file = 비디오 파일
image-file = 이미지 파일
email-file = 이메일 파일
code-file = 소스 코드
transcoding = 트랜스코딩 중
from = 보낸 사람
to = 받는 사람
subject = 제목
attachments = 첨부 파일
no-file-selected = 선택된 파일 없음
back-to-home = 홈으로 돌아가기
please-select-file = 볼 파일을 선택하세요
