choose-file = 파일 선택
zh-CN = 简体中文
en-US = English
ja-JP = 日本語
ko-KR = 한국어
es-ES = Español
fr-FR = Français
de-DE = Deutsch
supported-files = 지원 파일
drag-and-drop-file-here = 여기에 파일을 드래그 앤 드롭하세요
file = 파일
extension = 확장자
file-type-header = 파일 유형
extension-header = 확장자
category-header = 카테고리
pdf-file = PDF 파일
word-file = Word 문서
excel-file = Excel 스프레드시트
powerpoint-file = PowerPoint 프레젠테이션
rtf-file = 서식 있는 텍스트 문서
opendocument-file = OpenDocument 파일
slide = 슬라이드
markdown-file = Markdown 문서
epub-file = EPub 파일
mobi-file = Mobi 파일
azw3-file = Azw3 파일
archive-file = 압축 파일
guitar-tab-file = 기타 탭 파일
threed-model-file = 3D 모델 파일
loading = 로딩 중
loading-failure = 로딩 실패
password-dialog-title = 비밀번호
password-label = 비밀번호
password-input =
  .placeholder = 비밀번호 입력
submit = 제출
torrent-file = Torrent 파일
download = 다운로드
preview = 미리보기
prev = 이전
next = 다음
speaker-notes = 발표자 노트
empty-sheet = 이 시트는 비어 있습니다
sizes = 크기
paragraph = 단락
characters = 문자
numbers = 숫자
symbols = 기호
project-privacy-statement = 이 웹사이트는 개인 프로젝트입니다. 파일 미리보기를 위해 만들어졌습니다. 파일은 어디에도 업로드하거나 저장하지 않습니다. 클라우드 스토리지로 사용하지 마세요.
support-and-feedback-statement = 완전히 테스트되지 않았기 때문에 일부 파일, 특히 큰 파일을 열 때 문제가 발생할 수 있습니다. 문제를 발견하면 Github에서 이슈를 만들 수 있지만, 즉시 수정된다는 보장은 없습니다.
offline-support-statement = 이 웹사이트가 완전히 로드되면 브라우저를 재설치하거나 브라우저 저장소를 지우지 않는 한 오프라인에서 작동합니다.
default-viewer = 기본 뷰어
text = 텍스트
binary = 바이너리
file-is-too-large = 파일이 너무 큽니다
csv-file = CSV 파일
sqlite-file = SQLite 데이터베이스
tables = 테이블
rows = 행
columns = 열
empty-table = 이 테이블은 비어 있습니다
select-table = 데이터를 보려면 테이블을 선택하세요
wasm-file = WASM 파일
audio-file = 오디오 파일
video-file = 비디오 파일
subtitle-file = 자막 파일
subtitles = 개 자막
image-file = 이미지 파일
email-file = 이메일 파일
code-file = 소스 코드
ical-file = 캘린더/연락처 파일
calendar-events = 캘린더 이벤트
events = 개 이벤트
contacts = 연락처
contacts-count = 명
comic-file = 만화책 아카이브
single-page = 단일 페이지
double-page = 양면 페이지
tree-file = 구조화 데이터 파일
expand-all = 모두 펼치기
collapse-all = 모두 접기
search = 검색...
nodes = 개 노드
log-file = 로그 파일
search-logs = 로그 검색...
showing = 표시 중
lines = 줄
no-results = 일치하는 항목이 없습니다
empty-log = 표시할 로그 항목이 없습니다
config-file = 설정 파일
sections = 섹션
empty-config = 설정 항목을 찾을 수 없습니다
hex-file = 바이너리 파일
offset = 오프셋
ascii = ASCII
bytes-per-row = 행당 바이트
jump-to = 이동
loaded = 로드됨
truncated = 잘림
diff-file = Diff/Patch 파일
files-changed = 개 파일 변경됨
additions = 추가
deletions = 삭제
new = 신규
deleted = 삭제됨
renamed = 이름 변경
binary = 바이너리
binary-file = 바이너리 파일은 표시되지 않음
empty-diff = diff 내용을 찾을 수 없음
certificate-file = 인증서 파일
certificate = 인증서
private-key = 개인 키
public-key = 공개 키
certificate-request = 인증서 요청
fingerprints = 지문
raw-content = 원시 콘텐츠
word-wrap = 자동 줄바꿈
transcoding = 트랜스코딩 중
from = 보낸 사람
to = 받는 사람
subject = 제목
attachments = 첨부 파일
no-file-selected = 선택된 파일 없음
back-to-home = 홈으로 돌아가기
back = 뒤로
menu = 메뉴
switch-theme = 테마
please-select-file = 볼 파일을 선택하세요
open-source-credits = 오픈소스 크레딧
credits-intro = Web Explorer는 거인의 어깨 위에 구축되었습니다. 이 애플리케이션을 가능하게 해준 모든 오픈소스 프로젝트에 감사드립니다.
credits-footer = 오픈소스 소프트웨어로 사랑을 담아 제작
contact = 문의하기
feedback = 피드백
unsupported-file = 지원되지 않는 파일 형식
unsupported-file-message = 이 파일 형식은 현재 지원되지 않습니다. 이 형식의 지원을 원하시면 알려주세요!
request-support = 지원 요청

# 입력 영역
drop-or-paste = 파일을 놓거나 콘텐츠 붙여넣기
drop-paste-hint = 파일을 드래그 앤 드롭하거나 Ctrl+V로 붙여넣기

# 테마 전환
switch-to-light = 라이트 모드로 전환
switch-to-dark = 다크 모드로 전환

# Fiddler 뷰어
fiddler-file = Fiddler 세션 아카이브
sessions = 세션
method = 메서드
url = URL
status = 상태
request = 요청
response = 응답
timers = 타이머
headers = 헤더
body = 본문
no-sessions = HTTP 세션을 찾을 수 없습니다
select-session = 세부 정보를 보려면 세션을 선택하세요

# 클립보드 뷰어
clipboard-file = 클립보드 데이터
formats-available = 형식 사용 가능
html-source = HTML 소스
failed-to-parse-clipboard = 클립보드 데이터 구문 분석 실패
no-data = 데이터 없음
clear = 지우기
